services:

  adguardhome:
    image: docker.io/adguard/adguardhome:beta
    container_name: adguardhome
    hostname: adguardhome
    restart: unless-stopped
    networks:
      - bunni_network
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /mnt/Docker/Apps/AdGuardHome/config:/opt/adguardhome/conf
      - /mnt/Docker/Apps/AdGuardHome/work:/opt/adguardhome/work
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 20012:3000
    healthcheck:
      test: "/bin/netstat -pant | /bin/grep 53"
      interval: 45s
      timeout: 30s
      retries: 3

  adguardhome-sync:
    image: lscr.io/linuxserver/adguardhome-sync:latest
    container_name: adguardhome-sync
    hostname: adguardhome-sync
    restart: unless-stopped
    networks:
      - bunni_network
    depends_on:
      adguardhome:
        condition: service_healthy
        required: true
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /mnt/Docker/Apps/AdGuardHomeSync:/config
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro

networks:
  bunni_network:
    external: true
