volumes:
  flaresolverr:

services:

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    hostname: flaresolverr
    restart: unless-stopped
    networks:
      - bunni_network
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - flaresolverr:/config
    ports:
      - 20019:8191

  prowlarr:
    image: ghcr.io/hotio/prowlarr:nightly
    container_name: prowlarr
    hostname: prowlarr
    restart: unless-stopped
    networks:
      - bunni_network
    depends_on:
      flaresolverr:
        condition: service_started
        required: true
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UMASK_SET=002
    volumes:
      - /mnt/Docker/Apps/Prowlarr:/config
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 20049:9696
    healthcheck:
      test: ["CMD-SHELL", "curl -fSs http://localhost:9696/ping | jq -r .status || exit 1"]
      interval: 10s
      retries: 3
      start_period: 1m
      timeout: 10s
    labels:
      - "com.centurylinklabs.watchtower.depends-on=postgres"

  radarr:
    image: ghcr.io/hotio/radarr:nightly
    container_name: radarr
    hostname: radarr
    restart: unless-stopped
    networks:
      - bunni_network
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UMASK_SET=002
    volumes:
      - /mnt/Docker/Apps/Radarr:/config
      - /mnt/Abyss:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 20023:7878
    healthcheck:
      test: ["CMD-SHELL", "curl -fSs http://localhost:7878/ping | jq -r .status || exit 1"]
      interval: 10s
      retries: 3
      start_period: 1m
      timeout: 10s
    labels:
      - "com.centurylinklabs.watchtower.depends-on=postgres"

  sonarr:
    image: ghcr.io/hotio/sonarr:nightly
    container_name: sonarr
    hostname: sonarr
    restart: unless-stopped
    networks:
      - bunni_network
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UMASK_SET=002
    volumes:
      - /mnt/Docker/Apps/Sonarr:/config
      - /mnt/Abyss:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 20048:8989
    healthcheck:
      test: ["CMD-SHELL", "curl -fSs http://localhost:8989/ping | jq -r .status || exit 1"]
      interval: 10s
      retries: 3
      start_period: 1m
      timeout: 10s
    labels:
      - "com.centurylinklabs.watchtower.depends-on=postgres"

  recyclarr:
    image: ghcr.io/recyclarr/recyclarr:latest
    container_name: recyclarr
    hostname: recyclarr
    restart: unless-stopped
    networks:
      - bunni_network
    depends_on:
      - sonarr
      - radarr
      - prowlarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /mnt/Docker/Apps/Recyclarr:/config
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    labels:
      - "com.centurylinklabs.watchtower.depends-on=sonarr,radarr,prowlarr"

networks:
  bunni_network:
    external: true
