services:

  watchtower:
    image: ghcr.io/nicholas-fedor/watchtower:latest-dev
    container_name: watchtower
    hostname: watchtower
    restart: unless-stopped
    networks:
      - bunni_network
    environment:
      - TZ=${TZ}
      - WATCHTOWER_CLEANUP=${WATCHTOWER_CLEANUP}
      - WATCHTOWER_SCHEDULE=${WATCHTOWER_SCHEDULE}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    labels:
      - "com.centurylinklabs.watchtower.enable=false"

networks:
  bunni_network:
    external: true
